name: Buildathon
main: com.Buildathon.Buildathon
version: 1.0
author: kuuy
description: Minecraft Buildathon plugin for the 2020 UB Hackathon
api-version: 1.16
commands:
  buildathon:
    description: Main Buildathon command
    usage: /buildathon
    permission: buildathon.use
    permission-message: You don't have permission to use this command.

permissions:
  buildathon.use:
    description: Allow players to use the /buildathon command
    default: op